### ISSUE TITLE
Parser fails on some comments 

### ISSUE THREAD

**Issue by jackrusher** [venantius/glow#12] opened 2019-04-30 10:58 UTC
Hi! I just had a play with glow as a lighter alternative to running `pygments` in Jython, but I ran into a bug that was a showstopper for my use case. Example: `(glow/highlight ";; king:queen::man:[woman, Attempted abduction, teenager, girl]")` will not parse because the grammar appears to be trying to match clojure-like syntax in comment bodies.

**Comment by venantius** [comment] 2019-04-30 12:25
Yeah, this is definitely a bug. There's something about highlighting a string that begins with a comment that immediately causes the parser to think it's interpreting symbols instead of a comment - I'm not sure why.

Simple debugging:
```clojure
user=> (glow.parse/parse ";; king:queen::man")
(:file
 (:form (:literal (:symbol (:simple_sym ";;"))))
 (:form (:whitespace " "))
 (:form (:literal (:symbol (:simple_sym "king:queen"))))
 (:form (:literal (:keyword "::man"))))
```

That should be parsing as `(:file (:form (:comment "...etc")))`. I'm not sure why it's parsing `;;` as a symbol but that's the place to fix this - probably in the antlr grammar for `SYMBOL_HEAD`.

**Comment by venantius** [comment] 2019-04-30 12:28
Sorry - maybe not a bug, but not quite working as intended either. So the reason the grammar fails actually is because your comment isn't terminated with a newline - without a newline terminator it doesn't know the comment has ended. Maybe that should be newline or EOF?

This works fine: 
```clojure
user=> (glow.core/highlight ";; king:queen::man:[woman, Attempted abduction, teenager, girl]\n")
";; king:queen::man:[woman, Attempted abduction, teenager, girl]\n"
```

**Comment by venantius** [comment] 2019-04-30 13:21
This has now been resolved by https://github.com/venantius/glow/commit/ff64dba60c9f7649ee0804aa807525c5ea832683. I've cut a new release - 0.1.6 - that incorporates the bugfix.

**Closed by venantius** 2019-04-30 13:21 UTC

**Comment by jackrusher** [comment] 2019-04-30 14:04
Thanks for the speedy diagnosis and fix!
